#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu machine
sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
