#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu machine
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
# echo "Hello World!" | sudo tee /var/www/html/index.html
# OR
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
