#!/usr/bin/env bash
# This script generates a fictional story based on the /etc/passwd file.

# Read the /etc/passwd file line by line using a while loop + IFS
while IFS=':' read -r username password uid gid info home shell; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
