#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

# Initialize hour and minute variables
hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hr"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( hour++ ))
done
